### ISSUE TITLE
End-to-end test 'stack' fails

### ISSUE THREAD

**Issue by aweinert** [aweinert/coolc#4]
The end-to-end test `stack` with input `1` fails. During the execution, the JVM throws 

    Exception in thread "main" java.lang.NullPointerException
	at CoolString.equals(CoolString.java:26)
	at CoolMain.main(Unknown Source)
	at CoolMain.main(Unknown Source)

The user should never see Java-errors, they should be caught by the `cool`-runtime. Moreover, this error does not occur when running the program interactively.

**Comment by aweinert** [comment]
This only occurs if the input is piped into the program, i.e., when executing `java -jar out.jar < src/test/resources/end2end/stack/1.in`. When executing the program and providing the input by hand, the test works as intended
